spring.application.name=calculator-app
server.port=${PORT:8080}

# Enable the H2 Console so you can see your data at /h2-console
spring.h2.console.enabled=true

# Standard H2 In-Memory connection string
spring.datasource.url=jdbc:h2:mem:calculator_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
