spring.application.name=calculator-app
server.port = ${PORT:8080}
spring.datasource.url=postgresql://calculator_repository_user:6YLsyY6FjzYCS88OPJbqVLKHaNAAH4Sx@dpg-d5ijf8khg0os738lb7g0-a.oregon-postgres.render.com/calculator_repository
spring.datasource.username=calculator_repository_user
spring.datasource.password=6YLsyY6FjzYCS88OPJbqVLKHaNAAH4Sx
spring.jpa.hibernate.ddl-auto=update